/* Generated by Yosys 0.29+11 (git sha1 d82bae32b, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

module decoder2to4(a0, a1, d0, d1, d2, d3);
  input a0;
  wire a0;
  input a1;
  wire a1;
  output d0;
  wire d0;
  output d1;
  wire d1;
  output d2;
  wire d2;
  output d3;
  wire d3;
  sky130_fd_sc_hd__nor2_1 _0_ (
    .A(a0),
    .B(a1),
    .Y(d0)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1_ (
    .A(a0),
    .SLEEP(a1),
    .X(d1)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _2_ (
    .A(a1),
    .SLEEP(a0),
    .X(d2)
  );
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(a0),
    .B(a1),
    .X(d3)
  );
endmodule
